### PR TITLE
Blawx Implementation

### PR DESCRIPTION
**Pull request by Gauntlet173**
#14

### CODE REVIEW

**Review by Br3nda — CHANGES_REQUESTED** [review]
Can you add some tests? The expected results are in https://github.com/ServiceInnovationLab/example-rules-as-code/tree/master/shared

And also add the test command into the circleci config.

**Comment by Gauntlet173** [comment]
Blawx is not a command-line tool, and doesn't have an API, yet. Automated testing of the code is difficult, still. One of the downsides of visual coding environments.

If you like, I can generate all the tests inside the code, so you can run them all when you load the code. It currently only contains one where you can modify the three parameters.

I'm not familiar with circleCI, so let me know what you need, in that context.

**Comment by Br3nda** [comment]
circleci is our CI. Add a job to the yaml here: 
https://github.com/ServiceInnovationLab/example-rules-as-code/blob/master/.circleci/config.yml

it can run the examples in the csv and check that Blawx is calculation the correct response.

**Comment by Gauntlet173** [comment]
Sorry, I wasn't clear.

Because Blawx is not a command-line tool (it's a visual web app), and because it does not have an API that I could send data to and test the responses from (yet), I would need to use some sort of BDD tool that has circleci integration, like cypress, to automate the tests.

I have no experience with BDD tools, so learning cypress is a big ask for a demo toy implementation.

If the tests are mandatory, then I'd rather wait until Blawx gets a public-facing API, and I'll write the tests in python with requests. But it will be a delay.

I can put a manual test inside the folder, that the user can run in 4 clicks. But if that's not good enough, let me know, and I'll do a different PR when the API is up and running.

Thanks.

**Comment by Br3nda** [comment]
How do you test code in blawx?

**Comment by Gauntlet173** [comment]
Here's an example. You would load the test .blawx file in the web interface, and you would get something like this:

image

Then you would choose "Menu", "Run Blawx Code", and the reasoner will say "Yes" if all the tests succeeded, and "No" if any of them failed.

That's a bare-bones example. It could be made more complicated if necessary.

**Comment by Gauntlet173** [comment]
PR just to give you the option of including it in the repo if you'd like, despite the fact it doesn't have code to automate the testing. In theory, you could write a python script or something to send a test request to the API, and calculate the results. But that would be using Python, not Blawx.

**Comment by Br3nda** [comment]
cool. let's merge it.

thank you for this work

**Pull request merged**
